# Generated by Django 3.2.8 on 2021-10-06 21:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='received date')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Text message',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TextMessageSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('opted_in', models.BooleanField(verbose_name='opted in')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'text message sign up',
            },
        ),
    ]
