# Generated by Django 3.2.8 on 2021-10-06 04:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'unconfirmed'), (1, 'email confirmed only'), (2, 'phone number confirmed only'), (3, 'both email and phone number confirmed'), (4, 'opted out')], default=0, verbose_name='confirmation status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'Notification sign up',
            },
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='received date')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Text message',
                'ordering': ('-created',),
            },
        ),
    ]
