#!/bin/bash

set -e

PUBLIC_VARS="DOMAIN_NAME UMAMI_WEBSITE_ID"

echo -e "# Generated by Docker entrypoint. Do not modify this file, all changes will be lost!\n" > /app/.env

# Write out PUBLIC environment variables for sveltekit
for PUBLIC_VAR in $PUBLIC_VARS; do
    echo "PUBLIC_${PUBLIC_VAR}=\"${!PUBLIC_VAR}\"" >> /app/.env
done

if [ "$#" = 0 ]; then
    if [ -z "$DEV_MODE" -o "$DEV_MODE" = '0' ]; then
        echo 'Copying static files to /static/frontend'
        rsync -a --delete /app/build/client/ /static/frontend
        PROTOCOL_HEADER=x-forwarded-proto PORT=8000 exec node -r dotenv/config build
    else
        npm install
        exec npm run dev -- --port 8000 --host
    fi
else
    echo "Executing: $*"
    exec "$@"
fi
