FROM ubuntu:20.04

ARG COMPOSE_VERSION=2.0.1

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        wget \
    && rm -rf /var/lib/apt/lists/*

RUN wget -qO - https://get.docker.com/ | sh \
    && wget -qO /usr/libexec/docker/cli-plugins/docker-compose \
        "https://github.com/docker/compose/releases/download/v${COMPOSE_VERSION}/docker-compose-linux-$(arch)" \
    && chmod +x /usr/libexec/docker/cli-plugins/docker-compose

COPY --from=msoap/shell2http /app/shell2http /usr/local/bin/

RUN mkdir /app
WORKDIR /app

CMD shell2http -host 0.0.0.0 -form -export-vars COMPOSE_PROJECT_NAME \
    '/containers/list' 'docker compose config --services ; echo "== UP ==" ; docker compose ps --services --filter "status=running"' \
    '/containers/restart' 'docker compose restart "$v_container"'
