# Generated by Django 3.2.8 on 2021-10-27 22:37

import datetime
from django.db import migrations, models
import recurrence.fields
import s3direct.fields
import shows.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='A blank value defaults to the name of the show, which is a sane default. Specify something here to override that, ie for podcasts, named or special shows.', max_length=255)),
                ('show', models.CharField(choices=[('showgram', 'The Late Showgram w/ Jim Richards'), ('twwit', 'That Went Well, I Think w/ David Cooper'), ('tigwit', 'This Is Going Well, I Think w/ David Cooper'), ('bmir', 'Burning Man Information Radio (BMIR)'), ('misc', 'Misc. & Guest Appearances')], max_length=8)),
                ('published', models.BooleanField(default=True, help_text='Whether to show this entry on the actual website. Leave unchecked for draft mode.')),
                ('date', models.DateField(default=shows.utils.today_in_default_timezone, help_text='Time in <strong>US/Eastern</strong>.', verbose_name='date')),
                ('duration', models.DurationField(default=datetime.timedelta(0), help_text='In <code>HH:MM:SS</code> format. Leave 00:00:00 to autofill from file.')),
                ('description', models.TextField(blank=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, help_text='GUID for podcast. Automatically generated.', unique=True)),
                ('asset_url', s3direct.fields.S3DirectField(help_text='Upload audio asset here directly to DigitalOcean Spaces (S3). In mp3 format only.', verbose_name='audio asset')),
            ],
            options={
                'ordering': ('-date', 'show'),
            },
        ),
        migrations.CreateModel(
            name='ShowDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='A blank value defaults to the name of the show, which is a sane default. Specify something here to override that, ie for podcasts, named or special shows.', max_length=255)),
                ('show', models.CharField(choices=[('showgram', 'The Late Showgram w/ Jim Richards'), ('twwit', 'That Went Well, I Think w/ David Cooper'), ('tigwit', 'This Is Going Well, I Think w/ David Cooper'), ('bmir', 'Burning Man Information Radio (BMIR)'), ('misc', 'Misc. & Guest Appearances')], max_length=8)),
                ('published', models.BooleanField(default=True, help_text='Whether to show this entry on the actual website. Leave unchecked for draft mode.')),
                ('start_time', models.TimeField(help_text='Time in <strong>US/Eastern</strong>.', verbose_name='start time')),
                ('duration', models.DurationField(help_text='In <code>HH:MM:SS</code> format.')),
                ('dates', recurrence.fields.RecurrenceField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['date'], name='shows_episo_date_c511c9_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['show', 'date'], name='shows_episo_show_11fe8d_idx'),
        ),
    ]
