# Generated by Django 3.2.8 on 2021-10-26 07:53

from django.db import migrations, models
import recurrence.fields
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='A blank value defaults to the name of the show (used for special content).', max_length=255)),
                ('show', models.CharField(choices=[('showgram', 'The Late Showgram w/ Jim Richards'), ('twwit', 'That Went Well, I Think w/ David Cooper'), ('tigwit', 'This Is Going Well, I Think w/ David Cooper'), ('bmir', 'Burning Man Information Radio (BMIR)'), ('misc', 'Miscellaneous & Guest Apperances')], max_length=8)),
                ('published', models.BooleanField(default=True)),
                ('start', models.DateTimeField(db_index=True, verbose_name='start date')),
                ('duration', models.DurationField()),
                ('description', models.TextField()),
                ('asset_url', s3direct.fields.S3DirectField(verbose_name='audio asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='A blank value defaults to the name of the show (used for special content).', max_length=255)),
                ('show', models.CharField(choices=[('showgram', 'The Late Showgram w/ Jim Richards'), ('twwit', 'That Went Well, I Think w/ David Cooper'), ('tigwit', 'This Is Going Well, I Think w/ David Cooper'), ('bmir', 'Burning Man Information Radio (BMIR)'), ('misc', 'Miscellaneous & Guest Apperances')], max_length=8)),
                ('published', models.BooleanField(default=True)),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('duration', models.DurationField()),
                ('dates', recurrence.fields.RecurrenceField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
