# Generated by Django 4.0.1 on 2022-01-09 03:38

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='peaks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='episode',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, help_text='For podcast. Automatically generated.', unique=True, verbose_name='GUID'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('show_code', 'slug')},
        ),
    ]
