# Generated by Django 3.2.7 on 2021-09-20 23:14

import django.core.validators
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='In slug format, ie "placeholder.content"', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_\\.\\-]+$', message='Must contain only numbers, letters, periods or hyphens')], verbose_name='block name')),
                ('content', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
