FROM ubuntu:20.04

ARG COMPOSE_VERSION=2.0.1

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        wget \
    && rm -rf /var/lib/apt/lists/*

RUN wget -qO - https://get.docker.com/ | sh \
    && wget -qO /usr/libexec/docker/cli-plugins/docker-compose \
        https://github.com/docker/compose/releases/download/v${COMPOSE_VERSION}/docker-compose-linux-aarch64 \
    && chmod +x /usr/libexec/docker/cli-plugins/docker-compose

COPY --from=msoap/shell2http /app/shell2http /usr/local/bin/

RUN mkdir /app
WORKDIR /app

CMD [ "shell2http", "-host", "0.0.0.0", \
      "/restart/radio", "docker compose restart radio", \
      "/restart/radio-uplink", "docker compose restart radio-uplink" \
]
