# Generated by Django 3.2.6 on 2021-08-27 23:33

from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('recurrences', recurrence.fields.RecurrenceField()),
            ],
        ),
    ]
